#!/usr/bin/env python

#import rospy

import OPi.GPIO as GPIO
import time

GPIO.setboard(GPIO.PCPCPLUS)
# Set the GPIO modes
GPIO.setmode(GPIO.BCM)
# GPIO.setwarnings(False)

_FREQUENCY = 20

# 11- left forward

all_pins = [11, 65, 66, 19, 7, 8, 9, 10, 20, 13, 14, 110, 68, 71, 2, 67, 21, 18, 200, 201, 198, 199]


def main():
    while (1):
        i = 0
        while i < len(all_pins):
            print(i)
            print("\n")
            GPIO.setup(all_pins[i], GPIO.OUT)
            GPIO.output(all_pins[i], GPIO.HIGH)
            time.sleep(0.5)
            GPIO.output(all_pins[i], GPIO.LOW)
            i += 1


if __name__ == '__main__':
    main()
