#!/usr/bin/env python

#import rospy

import OPi.GPIO as GPIO
import time

GPIO.setboard(GPIO.PCPCPLUS)
# Set the GPIO modes
GPIO.setmode(GPIO.BCM)
# GPIO.setwarnings(False)

_FREQUENCY = 20

# 6 - left forward
# 19 - right forward
# 13 - left backward
#

all_pins = [12, 11, 6, 1, 0, 3, 19, 7, 8, 9, 10, 20, 13, 14, 67, 21, 18, 200, 201, 198, 199]


def main():
    while (1):
        i = 0
        while i < len(all_pins):
            print(all_pins[i])
            print("\n")
            GPIO.setup(all_pins[i], GPIO.OUT)
            GPIO.output(all_pins[i], GPIO.HIGH)
            time.sleep(2)
            GPIO.output(all_pins[i], GPIO.LOW)
            i += 1


if __name__ == '__main__':
    main()
