#!/usr/bin/env python

#import rospy

import OPi.GPIO as GPIO
import time

GPIO.setboard(GPIO.PCPCPLUS)
# Set the GPIO modes
GPIO.setmode(GPIO.BCM)
# GPIO.setwarnings(False)

_FREQUENCY = 20

# 6 - left forward
# 19 - right forward
# 13 - left backward
#

# 

all_pins2 = [12, 11, 6, 1, 0, 3, 64, 65, 66, 19, 7, 8, 9, 10, 20, 13, 14, 110, 68, 71, 2, 67, 21, 18, 200, 201, 198, 199]
all_pins = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]

def main():
    while (1):
        i = 0
        while i < len(all_pins):
            print(all_pins[i])
            print("\n")
            try:
                GPIO.setup(all_pins[i], GPIO.OUT)
                GPIO.output(all_pins[i], GPIO.HIGH)
                time.sleep(2)
                GPIO.output(all_pins[i], GPIO.LOW)
            except ValueError:
                time.sleep(0)
            i += 1


if __name__ == '__main__':
    main()
