footprint: [[0.2, -0.15],
            [0.2, 0.55],
            [-0.2, 0.55],
            [-0.2, -0.15]]

controller_frequency: 2.0
controller_patience: 5.0
clearing_radius: 0.25
footprint_padding: 0.03
recovery_behavior_enabled: false
